[package]
name = "cavif"
description = "Encodes images in AVIF format (image2avif converter). Pure Rust."
version = "0.4.0"
authors = ["Kornel Lesiński <kornel@geekhood.net>"]
edition = "2018"
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["avif", "png2avif", "jpeg2avif", "convert", "av1"]
categories = ["command-line-utilities", "multimedia::images", "multimedia::encoding"]
homepage = "https://lib.rs/cavif"
repository = "https://github.com/kornelski/cavif"
include = ["README.md", "LICENSE", "Cargo.toml", "/src/*.rs"]

[dependencies]
avif-serialize = "0.6.4"
clap = "2.33.3"
lodepng = "3.2.1"
num_cpus = "1.13.0"
pico-args = "0.3.4"
rav1e = { git = "https://github.com/xiph/rav1e" }
rayon = "1.4.0"
nasm-rs = "=0.1.7"
rgb = "0.8.25"
cocoa_image = { version = "1.0.4", optional = true }
imgref = "1.7.0"
jpeg-decoder = "0.1.20"
loop9 = "0.1.3"

[profile.dev.package.rav1e]
opt-level = 2

[profile.dev.package.lodepng]
opt-level = 2

[dev-dependencies]
avif-parse = "0.12.2"
